sudo: required
services:
  - docker

before_install:
  - docker build -t fvincenti73/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true fvincenti73/docker-react npm run test 

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker"
  env: "docker-env"
  bucket_name: "elasticbeanstalk-eu-west-1-377313891017"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  
